services:
  backend:
    build:
      context: ./backend
    environment:
      LOG_LEVEL: info
      HTTP_SHUTDOWN_DELAY: 3s
    ports:
      - "8080:8080"
    restart: unless-stopped

  web:
    build:
      context: ./frontend
    ports:
      - "3000:8080"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
