#!/usr/bin/env bash
# Prints a Markdown coverage summary built from
#   <dir>/backend/coverage.out             go test -coverprofile output
#   <dir>/frontend/coverage-summary.json   Vitest "json-summary" reporter output
# and exits 1 when backend statement coverage is below <min> percent overall, or below
# <domain-min> percent in any domain package (internal/* except the infrastructure
# packages app, config, httpapi, server and storage).
# Frontend thresholds are enforced by Vitest itself (vitest.config.ts).
#
# When <dir>/backend/bench.txt (go test -bench output) exists, a Benchmarks section lists
# every case and the script exits 1 if any case exceeds <bench-max-ms> milliseconds per
# operation (the calculator spec requires < 5 ms per worst case).
#
# Usage: scripts/coverage-report.sh [coverage-dir] [backend-min-percent] [domain-min-percent] [bench-max-ms] > docs/coverage.md
set -euo pipefail

dir="${1:-coverage}"
min="${2:-80}"
domain_min="${3:-90}"
bench_max_ms="${4:-5}"
infra_re='/internal/(app|config|httpapi|server|storage)(/|$)'
profile="$dir/backend/coverage.out"
summary="$dir/frontend/coverage-summary.json"
bench="$dir/backend/bench.txt"
status=0

echo "# Test coverage"
echo
echo "Generated by \`make coverage\`. Browse the HTML reports locally:"
echo "\`$dir/backend/index.html\` and \`$dir/frontend/index.html\`."
echo

if [[ -f "$profile" ]]; then
  echo "## Backend (Go, statements)"
  echo
  echo "| Package | Statements | Covered | Coverage |"
  echo "|---|---:|---:|---:|"
  total_file="$(mktemp)"
  low_file="$(mktemp)"
  # A block can appear once per test binary (-coverpkg); count it once, covered if any run hit it.
  awk -v totalfile="$total_file" -v lowfile="$low_file" -v dmin="$domain_min" -v infra="$infra_re" '
    FNR == 1 && /^mode:/ { next }
    {
      key = $1; stmts[key] = $2
      if ($3 > 0) hit[key] = 1
    }
    END {
      for (k in stmts) {
        split(k, loc, ":"); pkg = loc[1]; sub(/\/[^\/]*$/, "", pkg)
        total[pkg] += stmts[k]; all += stmts[k]
        if (k in hit) { covered[pkg] += stmts[k]; allc += stmts[k] }
      }
      n = 0
      for (p in total) names[++n] = p
      for (i = 2; i <= n; i++) { v = names[i]; j = i - 1; while (j > 0 && names[j] > v) { names[j + 1] = names[j]; j-- } names[j + 1] = v }
      low = ""
      for (i = 1; i <= n; i++) {
        p = names[i]
        pc = (total[p] ? 100 * covered[p] / total[p] : 100)
        note = ""
        if (p ~ /\/internal\// && p !~ infra && pc < dmin + 0) {
          note = " (below " dmin "%)"
          low = low (low == "" ? "" : ", ") p
        }
        printf "| `%s` | %d | %d | %.1f%%%s |\n", p, total[p], covered[p], pc, note
      }
      printf "%s", low > lowfile
      pct = (all ? 100 * allc / all : 100)
      printf "| **Total** | **%d** | **%d** | **%.1f%%** |\n", all, allc, pct
      printf "%.1f\n", pct > totalfile
    }' "$profile"
  backend_total="$(cat "$total_file")"
  low_packages="$(cat "$low_file")"
  rm -f "$total_file" "$low_file"
  echo
  if awk -v t="$backend_total" -v m="$min" 'BEGIN { exit !(t + 0 < m + 0) }'; then
    echo "**Total below the ${min}% threshold.**"
    echo "backend coverage ${backend_total}% is below the ${min}% threshold" >&2
    status=1
  else
    echo "Total threshold: ${min}% (met)."
  fi
  echo
  if [[ -n "$low_packages" ]]; then
    echo "**Domain packages below ${domain_min}%:** ${low_packages}."
    echo "domain packages below the ${domain_min}% threshold: ${low_packages}" >&2
    status=1
  else
    echo "Domain package threshold: ${domain_min}% (met)."
  fi
  echo
else
  echo "_No backend profile at \`$profile\`._"
  echo
fi

if [[ -f "$summary" ]]; then
  echo "## Frontend (Vitest, V8)"
  echo
  node - "$summary" <<'NODE'
const fs = require('node:fs');
const total = JSON.parse(fs.readFileSync(process.argv[2], 'utf8')).total;
console.log('| Metric | Covered | Total | Coverage |');
console.log('|---|---:|---:|---:|');
for (const key of ['lines', 'statements', 'functions', 'branches']) {
  const m = total[key];
  const name = key[0].toUpperCase() + key.slice(1);
  console.log(`| ${name} | ${m.covered} | ${m.total} | ${Number(m.pct).toFixed(1)}% |`);
}
NODE
  echo
  echo "Thresholds are enforced in \`frontend/vitest.config.ts\`."
else
  echo "_No frontend summary at \`$summary\`._"
fi

if [[ -f "$bench" ]]; then
  echo
  echo "## Benchmarks (Go, evaluator worst cases)"
  echo
  echo "Measured by \`go test -bench=BenchmarkEvaluate\` on this machine; CI runs the same benchmark."
  echo
  echo "| Case | ns/op | ms/op |"
  echo "|---|---:|---:|"
  slow_file="$(mktemp)"
  awk -v maxms="$bench_max_ms" -v slowfile="$slow_file" '
    $1 ~ /^BenchmarkEvaluate\// && $(NF) == "ns/op" {
      name = $1; sub(/^BenchmarkEvaluate\//, "", name); sub(/-[0-9]+$/, "", name)
      ns = $(NF - 1); ms = ns / 1000000
      note = ""
      if (ms >= maxms + 0) { note = " (over " maxms " ms)"; slow = slow (slow == "" ? "" : ", ") name }
      printf "| `%s` | %d | %.3f%s |\n", name, ns, ms, note
    }
    END { printf "%s", slow > slowfile }' "$bench"
  slow_cases="$(cat "$slow_file")"
  rm -f "$slow_file"
  echo
  if [[ -n "$slow_cases" ]]; then
    echo "**Benchmark cases over the ${bench_max_ms} ms limit:** ${slow_cases}."
    echo "benchmark cases over the ${bench_max_ms} ms limit: ${slow_cases}" >&2
    status=1
  else
    echo "**Benchmark limit: ${bench_max_ms} ms per case (met).**"
  fi
fi

exit "$status"
